framework:
    test: ~
    session:
        enabled: true
        handler_id: 'session.handler.native_file'
    profiler: false
    mailer:
        transports:
            main: 'null://null'
            pimcore_newsletter: 'null://null'

web_profiler:
    toolbar: false
    intercept_redirects: false
